### ISSUE TITLE
test support/query split for MiniImageNet 

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [hushell/pmf_cvpr22#1]
First of all, thank you for providing the code! You've done brilliant work!
Since I need to test the meta-trained model on the test set of MiniImageNet, I wonder if you can provide the sup/query split link for test set as done for val set?
It will be grateful if you can address my problem, Thanks a lot!

**Comment by hushell** [comment]
Hi @LIUZIJING-CHN, 

We generate fixed val tasks to remove randomness in validation but meta-test is done on 600 randomly sampled tasks and report average accuracy. Randomness is allowed there so you may report std too.

**Comment by LIUZIJING-CHN** [comment]
I see，you use the same name for test/val set in the code. Thanks a lot!
