### ISSUE TITLE
ilsvrc2012 datasets

### ISSUE THREAD

**Issue by heekhero** [hushell/pmf_cvpr22#13]
Hi, great work! It seems that one subset of meta-datasets ILSVRC2012 provided in your hugging face page(https://huggingface.co/datasets/hushell/meta_dataset_h5/tree/master) is split into three parts, which are ended up with postfix .parta*. When separately unzipping these files with the command line instruction "tar -xvzf *", EOF error occurs! It seems that these files should be combined together first. So how to achieve this?

**Comment by hushell** [comment]
Hello, the split was due to file size limit on huggingface. Could you try this command? 
```
cat ilsvrc_2012.tar.gz.* | tar xzvf -
```
I haven't uncompressed the split files myself, will try when I go back to work.

**Comment by heekhero** [comment]
It seems that the combined file is incomplete, the process will be interrupted when about 700+ files are successfully got.

**Comment by hushell** [comment]
@heekhero Yes, I uncompressed myself today and it only has 759 h5 files... I'm uploading again the ilsvrc_2012 subset. It may take a few hours. Sorry for the inconvenience!

**Comment by heekhero** [comment]
Is the uploading process finished? The tag of files has not changed. It is still the version from 16 days ago.

**Comment by hushell** [comment]
@heekhero Sorry we got an network problem over the holidays and git lfs failed :/ I'll try again. 
I would recommend you guys to convert ImageNet1k by yourself at the moment following the [4 steps](https://github.com/hushell/pmf_cvpr22#meta-dataset)

**Comment by hushell** [comment]
@heekhero Finally the [ilsvrc_2012 h5 files](https://huggingface.co/datasets/hushell/meta_dataset_h5/tree/main/ilsvrc_2012) are pushed :)

**Comment by heekhero** [comment]
@hushell Thank you! I have successfully got the right files!
