### ISSUE TITLE
Problem in test_bscdfsl.py

### ISSUE THREAD

**Issue by YingYuChen97** [hushell/pmf_cvpr22#14]
![image](https://user-images.githubusercontent.com/78190023/209298493-d1f6eee3-4053-4123-b3f5-4f5af87c0df7.png)

while choosing the learning rates, the iterator of data_loader_val seems to stop at the last one after finish training with lr=0, so it's not able to train with lr=0.0001.
(I set the iter_num to 20 for experiment)

**Comment by hushell** [comment]
Hi @YingYuChen97 Sorry for late reply! I was on holidays. 
This seems like this [for loop](https://github.com/hushell/pmf_cvpr22/blob/main/engine.py#L134) is skipped, so `loss` is not computed, and therefore `metric_logger.loss` doesn't exist. You may need to check whether `data_loader_val` is correctly set up.
