### ISSUE TITLE
ilsvrc_2012 h5 files corrupt

### ISSUE THREAD

**Issue by YingYuChen97** [hushell/pmf_cvpr22#16]
![image](https://user-images.githubusercontent.com/78190023/216808543-c2fbfb7d-1877-42d0-b1b7-ad4a74b4c026.png)

Please help check if the h5 files for ilsvrc_2012 in Meta-dataset is corrupted.
It doesn't happen on other sub-dataset in Meta-dataset.
 
Thanks!

**Comment by hushell** [comment]
Hi @YingYuChen97, 

The h5 file you can't open on my local seems fine. Could you try 
```
import h5py as h5
f = h5.File('~/data/meta_dataset/ilsvrc_2012/val_ep120_img128.h5', 'r')
print(f.keys())
```

**Comment by YingYuChen97** [comment]
![image](https://user-images.githubusercontent.com/78190023/216987031-5cfcaaf5-3411-45f2-8088-0d538e56b0db.png)

All other folders are fine, but ilsvrc_2012.
Could you upload it again? Thank you.

**Comment by hushell** [comment]
I downloaded `ilsvrc_2012/1.h5` on my local machine, which works fine. 
I doubt it's something else, e.g.: https://github.com/h5py/h5py/issues/757#issuecomment-356206021

**Comment by YingYuChen97** [comment]
@hushell  just to note that your files on hugging face are fine, and thanks for your patience.
First I need to install ***git lfs*** following https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md , then I can download all the files properly.
