### ISSUE TITLE
About fine-tuing on MiniImageNet

### ISSUE THREAD

**Issue by bityangke** [hushell/pmf_cvpr22#17]
Thank you very much for contributing such a good code base for FSL. 
In the paper, did you use fine-tuning on Mini imagenet?

**Comment by hushell** [comment]
Thank you for your interests! For Mini-ImageNet, the fine-tuning step was skipped as the performance was too good due to pre-trained ViT. I'm pretty sure fine-tuning will push the performance to ~100%
