### ISSUE TITLE
pretrained_model

### ISSUE THREAD

**Issue by KyleWang-Hunter** [hushell/pmf_cvpr22#2]
can you share your pretrained_model?

**Comment by VicaYang** [comment]
An impressive work! Could you share the weights of the model (pretrained version and pretrained + meta-trained version)

**Comment by KyleWang-Hunter** [comment]
> 

how to test on  a new image？

**Comment by hushell** [comment]
Thanks for your interests! I'll need to figure out the internal code permission for the checkpoint release. Stay tuned :)

To test with a DINO-small version, please check our gradio demo: https://huggingface.co/spaces/hushell/pmf_with_gis

**Comment by KyleWang-Hunter** [comment]
> Thanks for your interests! I'll need to figure out the internal code permission for the checkpoint release. Stay tuned :)
> 
> To test with a DINO-small version, please check our gradio demo: https://huggingface.co/spaces/hushell/pmf_with_gis

thank you , can not wait.

**Comment by hushell** [comment]
Hi guys, sorry for late! Please find a few checkpoints for Meta-Dataset: https://huggingface.co/hushell/pmf_metadataset_dino

**Comment by andylin12** [comment]
> Hi guys, sorry for late! Please find a few checkpoints for Meta-Dataset: https://huggingface.co/hushell/pmf_metadataset_dino

Sorry but the link above is missing, got a 404 error on huggingface. Could you help check?

Thanks in advance.

**Comment by hushell** [comment]
@andylin12 Oops... forgot to make the repo public :p
