### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by Goldit** [hushell/pmf_cvpr22#20]
I hope this message finds you well! I recently stumbled upon your amazing open source repository,  and I must say, I'm truly impressed with your work. I wanted to reach out and kindly request something important: adding a license to your repository. Your project has great potential, and by including a license, you can provide clarity and legal protection for users and contributors while fostering collaboration.

Would you consider adding a commonly used open source license, such as the MIT License or Apache License 2.0?

Thank you!

**Comment by hushell** [comment]
Thanks for the suggestion! I didn't attach a license as this repo is not officially a Samsung repo, but it is very likely a MIT license can be added.
