### ISSUE TITLE
Typo in command for Cross-domain few-shot learning

### ISSUE THREAD

**Issue by wilson-xu-dev** [hushell/pmf_cvpr22#26]
Hi there, 

Under README.md, last section (Cross-domain few-shot learning)

`python test_bscdfsl.py --test_n_way 5 --n_shot 5 --device cuda:0 --arch dino_small_patch16 --deploy finetune --output outputs/your_experiment_name --resume outputs/your_experiment_name/best.pth --ada_steps 100 --ada_lr 0.0001 --aug_prob 0.9 --aug_types color transition`

`aug_types color transition` should be `color translation`, using `transition` leads to Keyerror as augmentation does not exist.

**Comment by xbkaishui** [comment]
great thanks
