### ISSUE TITLE
can you share your pretrained_model?

### ISSUE THREAD

**Issue by bbcenglish** [hushell/pmf_cvpr22#3]
can you share your pretrained_model?

**Comment by hushell** [comment]
Thanks for your interests! I'll need to figure out the internal code permission for the checkpoint release. Stay tuned :)

**Comment by KyleWang-Hunter** [comment]
> Thanks for your interests! I'll need to figure out the internal code permission for the checkpoint release. Stay tuned :)

anything update? @hushell

**Comment by hushell** [comment]
@KyleWang-Hunter 
Sorry for late reply! Just uploaded 3 checkpoints on Meta-Dataset: https://huggingface.co/hushell/pmf_metadataset_dino
