### ISSUE TITLE
reproducibility on MiniImageNet and Cifar

### ISSUE THREAD

**Issue by Jerryaa98** [hushell/pmf_cvpr22#39]
Hey,

I'm trying to reproduce the result using a pre trained model that I can just load and test, but I see that you only put a trained model on the meta dataset, is there a pre trained VIT-s and VIT-b that I can download and run?

thanks

**Comment by hushell** [comment]
Hello, 

It's a bit hidden but all downloads are available here: https://github.com/hushell/pmf_cvpr22/blob/622d656afba5aeb39b70eaa3cceda74ad0b09faf/models/__init__.py#L9

**Comment by Jerryaa98** [comment]
Thanks for the quick reply.

I used your script for example on Cifar 
```
python main.py --dataset cifar_fs --epoch 100 --lr 5e-5 --arch dino_small_patch16 --device cuda:0 --nSupport 5 --fp16 --eval
```
and I got 59% for 1shot and 80% for 5 shot

for miniimageNet net I used the same command but instead of cifar-fs I pu miniimage and got 89% and 97% for 1shot and 5shot, it's still a bit far from the paper results, is the command right or do I have to load the weights manually?

**Comment by hushell** [comment]
Can you post your training logs? 

>  I got 59% for 1shot and 80% for 5 shot

This looks like the results using pre-trained ViT-small on CIFAR-FS. 

> miniimage and got 89% and 97% for 1shot and 5shot

This looks close to our results

**Comment by Jerryaa98** [comment]
I may have misunderstood, in table 2 of the paper are the results that I'm supposed to get? what are the differences between table 2 and table 4? because the results seem different I was looking at table 4
