### ISSUE TITLE
ImportError: cannot import name 'get_metadataset'

### ISSUE THREAD

**Issue by xssdss** [hushell/pmf_cvpr22#5]
I want to use metadata set for training, but when I generate val data, I run ‘generate_val_episodes_to_h5.py’ and it report an error：'ImportError: cannot import name 'get_metadataset''

in ’generate_val_episodes_to_h5.py‘, line 14, there is ‘from datasets import get_metadataset‘, but I also can’t find ‘get_metadataset’ anywhere.

**Comment by Totoro-wen** [comment]
@xssdss， Hi, I met the same problem. Did you solve the problem?

**Comment by hushell** [comment]
Sorry for super late reply @xssdss @Totoro-wen! I think I solve the issue. Please check [commit](https://github.com/hushell/pmf_cvpr22/commit/43f16a4bee1cacbe3b874a26561cb57b5bd0dc9a).
