### ISSUE TITLE
when I run 'convert_tfrecord_to_h5.py'

### ISSUE THREAD

**Issue by Yxt1212** [hushell/pmf_cvpr22#6]
There is a OSError,ilsvrc_2012/0.index not found, please tell me how to solve this problem.Or you can provide a link for downloading the h5 files.Thanks

**Comment by anish9** [comment]
@Yxt1212, The fix can be found here, ```https://github.com/mboudiaf/pytorch-meta-dataset```, generate the index files given the tfrecord folder.
In my case I customized the following lines in Makefile to:
```
index_files:
	
	source_path=/home/anish/anish/pytorch-meta-dataset/omniglot/omniglot/; #${RECORDS}/$${source} ;\
	find $${source_path} -name '*.tfrecords' -type f -exec sh -c '$(exec)3 -m tfrecord.tools.tfrecord2idx $$2 $${2%.tfrecords}.index' sh $${source_path} {} \; ;\
```
example :  ```/home/anish/anish/pytorch-meta-dataset/omniglot/omniglot/*.tfrecords``` this is my tfrecord path

**Comment by hushell** [comment]
Thanks @anish9! Great finding! 

@Yxt1212 Sorry for missing the important step! Readme updated.
