### ISSUE TITLE
Can not download mini_imagenet and cifar_fs

### ISSUE THREAD

**Issue by huangluyao** [hushell/pmf_cvpr22#8]
wget https://www.dropbox.com/s/wuxb1wlahado3nq/cifar-fs-splits.zip?dl=0
--2022-08-25 19:20:49--  https://www.dropbox.com/s/wuxb1wlahado3nq/cifar-fs-splits.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 118.193.240.37, 2001::68f4:2e11
Connecting to www.dropbox.com (www.dropbox.com)|118.193.240.37|:443... 
Connecting to www.dropbox.com (www.dropbox.com)|118.193.240.37|:443... failed: Connection timed out.
Connecting to www.dropbox.com (www.dropbox.com)|2001::68f4:2e11|:443... failed: Network is unreachable.

**Comment by hushell** [comment]
Hi, 

Just tested. The download links still work for me. Perhaps it's a networking problem?
