### ISSUE TITLE
ImportError: cannot import name 'get_metadataset'

### ISSUE THREAD

**Issue by cosoldier** [hushell/pmf_cvpr22#9]
An impressive project!
Trying to reproduce your work, but I find a bug in the third step of preparing meta-dataset by runing scripts/generate_val_episodes_to_h5.py, 

Traceback (most recent call last):
  File "scripts/generate_val_episodes_to_h5.py", line 15, in <module>
    from datasets import get_metadataset
ImportError: cannot import name 'get_metadataset'

**Comment by Totoro-wen** [comment]
Hi.I have the same problem. Is there any good solution？

**Comment by ed-fish** [comment]
I used the FullMetaDatasetH5 class and it seems to be working. 

```py
 for j, source in enumerate(args.val_sources):
        if args.eval:
            dataset_val = FullMetaDatasetH5(args, Split["TEST"])
            h5_file = f'{source}/test_ep{args.nValEpisode}_img{args.image_size}.h5'
        else:
            dataset_val = FullMetaDatasetH5(args, Split["VALID"])
            h5_file = f'{source}/val_ep{args.nValEpisode}_img{args.image_size}.h5'
```

I have no idea if this creating the correct splits yet though - can anyone confirm?

**Comment by cosoldier** [comment]
Thanks for your answer. I guess the FullMetaDatasetH5 class can work, since the num_episodes of TEST split is also 600.

**Comment by hushell** [comment]
Hi @cosoldier @Totoro-wen @ed-fish, 

Thank you for your interests! This is indeed a missing function when I simplified the code for public release. I add this code back. Please check this [commit](https://github.com/hushell/pmf_cvpr22/commit/43f16a4bee1cacbe3b874a26561cb57b5bd0dc9a) for more details. 

I'll double check the code tomorrow and I'll upload the H5 files I generated.

**Comment by cosoldier** [comment]
> Hi @cosoldier @Totoro-wen @ed-fish,
> 
> Thank you for your interests! This is indeed a missing function when I simplified the code for public release. I add this code back. Please check this [commit](https://github.com/hushell/pmf_cvpr22/commit/43f16a4bee1cacbe3b874a26561cb57b5bd0dc9a) for more details.
> 
> I'll double check the code tomorrow and I'll upload the H5 files I generated.

Thank you!
